Resources:
  MainVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a
      Size: 8
      VolumeType: gp2

  DataStore:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-east-1a
      Size: 1
      VolumeType: gp2
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b69ea66ff7391e80
      InstanceType: t2.micro
      KeyName: mykey
      SecurityGroupIds:
        - sg-0a1b2c3d4e5f6g7h8
      SubnetId: subnet-0a1b2c3d4e5f6g7h8
      Tags:
        - Key: Name
          Value: TheInstance
      Volumes:
        - Device: /dev/sda1
          VolumeId: !Ref MainVolume
        - Device: /dev/sdf
          VolumeId: !Ref DataStore
      

  EBSSnapshot:
    Type: AWS::EC2::Snapshot
    Properties:
      Description: Snapshot of EBS volume
      VolumeId: !Ref DataStore
      